# Generated by Django 4.1.1 on 2022-10-15 21:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.FileField(upload_to=core.models.upload_path)),
            ],
        ),
        migrations.DeleteModel(name="Audio_store",),
    ]
