# Generated by Django 4.1.1 on 2022-10-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_audio_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="summary",
            field=models.CharField(blank=True, default="change this!", max_length=1000),
        ),
    ]
