# Generated by Django 4.1.1 on 2022-10-16 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_audio_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
