# Generated by Django 4.1.1 on 2022-10-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_audio_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="token",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
