services:
  backend:
    build: ./backend  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: python manage.py runserver 0.0.0.0:$PORT
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend