# Generated by Django 5.0.6 on 2024-09-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chatmessage_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='bot_response',
            new_name='bot_text',
        ),
    ]
