# Generated by Django 5.1.2 on 2024-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_bot_response_chatmessage_bot_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='bot_text',
            new_name='assignments_text',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='lectures_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='quizzes_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='summary_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
