# Generated by Django 5.1.2 on 2024-11-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_bot_text_chatmessage_assignments_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='summary_text',
            new_name='summary_content',
        ),
    ]
