# Generated by Django 5.1.2 on 2024-11-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_summary_text_chatmessage_summary_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='summary_content',
            new_name='summary_text',
        ),
    ]
